Implemented minigame
yuning-dev/22-munchies-game pull request #1
Opened 2024-05-28 12:34 UTC by yuning-dev

2024-05-31 11:15 UTC, JordanGlanfield requested changes

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-playground/canvas-playground.js
> +const canvas = document.getElementById('mainCanvas')
Experimental and testing stuff is best kept out of master as it's essentially dead code (unreachable or unusable code that clutters the codebase). If I'm experimenting with things I want to add to the code then each time I want to do something experimental I make a new branch called `experiment/<descriptive name of what I'm experimenting with>`. All experimental code goes into these branches. That way you can write them as modifications to your existing code rather than totally separate code

If you're experimenting with a bigger idea or approach then I'd make a separate "Proof of Concept" repo for them.

Could you put these files somewhere else and delete them from master?

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +let c = canvas.getContext('2d')
Can this be const?

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +const canvasY = 750
More descriptive names would be `canvasWidth` and `canvasHeight`. It's easier to read that way as `x` and `y` variables intuitively refer to locations rather than dimensions.

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +const gridSize = 25
A note for next time, using just one variable to represent the width and height of the grid is making an assumption that you will always want a square grid. If you used two variables from the start `gridWidthUnits` and `gridHeightUnits` (where units is used to specify that these are arbitrary unit dimensions rather than pixels) then it would be only a small amount of extra effort but would save significant time later if you changed your assumption about it being square

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +// min is inclusive, max is exclusive
nitpick: I think this is the conventional way of implementing random numbers and range checks so you could leave out the comment

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +function getRadians(degrees) {
If you take this function name out of context it's not clear what it does. For conversion functions naming it something like `degreesToRadians` can make it unambiguous as well as reading quite nicely when you call it

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +// }
Can delete this. Git keeps a history of all your meaningful code changes if you commit regularly, so there's no need to keep commented out code in general

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +        // console.log(JSON.stringify(ob))
delete

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +        this.center = { ...center }
Good thinking taking a copy of the properties rather than keeping a reference to the original object, which would be a code smell :)

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    drawCircle() {
Right now the Circle class is tightly coupled to the canvas global variable because you directly reference it in the class. You can break this coupling by adding a `canvas` parameter to `drawCircle` that is passed in. This would make refactorings and restructurings of your code easier over time

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    checkOverlapWithObjCenter(shapes) {
This function does the following:
1. Iterates through "shapes" to do processing (not clear what these shapes represent)
2. Checks for overlap
3. Deletes the shape from the array if there's overlap (side effect)
4. Conditionally increases the circle's size (side effect)
5. Redraws the whole canvas (side effect). Also it probably isn't the circle's responsibility or right to access the canvas in this way. If you imagine the ownership structure then currently it's as though your app owns the circle but the circle also owns the app. This can get very messy as you add more classes and give all of them the ability to produce side effects in the main app
6. Draws all the shapes (side effect). See point 5
7. Manages the game logic for when all the treats have been eaten by drawing the star

There's a structural design problem here in that your circle is managing game logic. If you think back to Vue components, this would be like making a stylish button child component that modifies state in the store, fires off actions, and changes properties of its parent. There's also a function design problem, in that this function does too many things and too many different types of things.

I would split out the overlap checking logic into a function in the Circle called `checkOverlapWithShape(shape)` that returns true or false based on whether the circle overlaps this one shape.

Then extract a function like the following.
```
// Iterates through treats, calls circle.checkOverlapWithShape(treat) on each treat. If the treat overlaps then remove it from the treats array and conditionally increase circle size. Call this in postDrawingCircle
handleTreatCollisions(circle, treats)
```

You can simply remove the logic that draws the treats and the star since this is already done by `redrawCanvas`.

More generally, when you're writing functions, try and describe to yourself what a function does. The easiest functions to write, maintain, and understand do only 1 thing, so that's the goal. If the function does multiple things, then ideally they'd all be of the same nature - like printing out multiple pieces of information related to one object for example. If you find your function is doing many different things, then try and split it up into smaller functions. A classic example is having a function that iterates through a list and does some logic with each item. Often the logic can be separated into its own function that handles only that logic or a subset of the logic for one item.

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    checkOverlapWithStar() {
Read the above comment first. You can reuse the overlap checking function here. Also, I would extract this function out of the Circle class because your Circle shouldn't be managing game logic like win conditions and when to display text, it should only manage Circle things :) E.g., its state and utility functions for checking for collisions with other objects, that kinda stuff.

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    checkOverlapWithCircle(circles) {
I would also extract this out of the Circle following the same pattern as extracting out `checkOverlapWithObjCenter`

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +                if (this.radius + 7.5 <= 150) {
I would extract these numbers into constants `CIRCLE_GROWTH_AMOUNT` and `MAX_CIRCLE_SIZE` respectively.

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    drawTreat() {
Can rename to just `draw()` since it's in the Treat class

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    drawMine() {
Rename to `draw`

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +class gameState {
This should be `GameState`. It's convention that all classes should have camel case with a capitalised first letter

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +let gameStateInst = new gameState(false, false)
Can be const and renamed to gameState after renaming the class

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +        }
Does the type of the entity and its shape characteristics actually matter? It seems to me that you could remove all of these if-statements and just use the following for all entities
```
entity.center.x = getRandomInt(0, canvasX - gridSize) + gridSize/2
entity.center.y = getRandomInt(0, canvasY - gridSize) + gridSize/2
```

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    // testTreat4.drawTreat()
delete

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    treats.length = 0
While assigning to the array's length is cool (I've never seen it before, hahah), I would do `treats = []` instead. Why keep the old array at all if what you want is a fresh, blank state. In general, prefer creating fresh objects and arrays when you're resetting state rather than updating properties of existing objects. Otherwise, you run the risk of keeping portions of the old state that you've forgotten about, and that can introduce subtle bugs.

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +    circle.center.x = 500
In line with the above, create fresh Circle and GameState object too. At the moment you're essentially duplicating the initialisation logic of Circle and GameState, which means any time you add a new property to either class you will also need to add that property's initial value here

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +function drawStar(center, spikes, outerRadius, innerRadius) {
When you copy utility functions from online it produces a readability problem if they don't match your codestyle. Could you update this to match the rest of your code? (no var, a space between variables and the equals sign, more spacing in general etc...)

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +        // if (!(entity instanceof Treat)) {
You can remove both of these if statements. If the code reaches this point then grid.has(gridString) must be false

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +class Treat {
Your Treat, Star, and Mine classes are nice and neat :)

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +        let obliqueY = Math.sin(getRadians(45)) * this.arm
Very nice 📐

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +function randomiseCanvasHalf(margin, canvasXY, circleRadius) {
Is using a random number to pick between two halves and then picking a random pixel within one of those halves functionally different from generating a random pixel from the whole?

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +}
Shouldn't a new grid map be generated too?

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +function updateGridCoordinates(entity) {
This name could mean anything XD Maybe `ensureEntityIsInEmptyGridSquare` would be more descriptive? It implies both a conditional check and side effects that will ensure that that condition is satisfied by the time the function completes

2024-05-31 11:15 UTC, JordanGlanfield commented on canvas-minigame.js
> +function postDrawingCircle(treats, mines) {
The pre and post drawing circle functions add some nice structure to your program. I would also add a `tick` function:

```
function tick() {
  preDrawingCircle(treats, mines)
  circle.drawCircle()
  postDrawingCircle(treats, mines)
}
```

That way instead of having to remember to call all three functions in multiple places, you can replace each set of calls with a single call to `tick()`. The name is a reference to the ticking of game engines, where every frame constitutes one tick.

Alternatively, you could call it `processFrame`, `redraw`, or something like that. Something that implies it's the top level game state processing function

2024-05-31 11:16 UTC, JordanGlanfield commented
Very nice getting all this working. It has a lot more business logic and structural complexity than anything you've built before and is quite a different style of coding :) I've added comments mostly on design structure, naming / readability, and some opportunities to cut down on duplication.

2024-06-04 09:42 UTC, yuning-dev commented on canvas-playground/canvas-playground.js
> +const canvas = document.getElementById('mainCanvas')
Got it, it's been addressed.

2024-06-04 09:52 UTC, yuning-dev commented on canvas-minigame.js
> +const gridSize = 25
Got it, thanks

2024-06-04 09:59 UTC, yuning-dev commented on canvas-minigame.js
> +// min is inclusive, max is exclusive
Leaving it in for now for my own reference :)

2024-06-04 10:04 UTC, yuning-dev commented on canvas-minigame.js
> +class gameState {
Nice catch

2024-06-04 10:10 UTC, yuning-dev commented on canvas-minigame.js
> +function drawStar(center, spikes, outerRadius, innerRadius) {
Cheers, fixed

2024-06-04 10:56 UTC, yuning-dev commented on canvas-minigame.js
> +    drawCircle() {
Implemented for all entities (Circle, Treat, Mine and Star)

2024-06-04 14:20 UTC, yuning-dev commented on canvas-minigame.js
> +    checkOverlapWithObjCenter(shapes) {
Thanks for the detailed explanation. I have refactored the functions from the Circle class to be only relevant to the remit of the Circle, by decoupling them from actions like changing circle size or checking for the win/loss status. I have simplified the code by removing the function to check overlap with the star as this can be done with a general purpose function (passing star as the argument). 

Good points in the last paragraph. Moving forward, I'll try and keep it in mind when designing functions :)

2024-06-04 14:22 UTC, yuning-dev commented on canvas-minigame.js
> +    checkOverlapWithStar() {
Addressed; see above

2024-06-05 08:38 UTC, yuning-dev commented on canvas-minigame.js
> +    drawTreat() {
Updated for all entities

2024-06-05 08:45 UTC, yuning-dev commented on canvas-minigame.js
> +    treats.length = 0
Makes sense, thanks for explaning. It's been addressed

2024-06-05 10:39 UTC, yuning-dev commented on canvas-minigame.js
> +let gameStateInst = new gameState(false, false)
Changed it back to let so gameStateInst can be assigned to a new GameState when resetting the game

2024-06-05 10:53 UTC, yuning-dev commented on canvas-minigame.js
> +        }
Implemented, along with updating topLeft.x and topLeft.y for treats, which solved a bug that would happen if 2 treats were initially spawned in the same place. Also redesigned the way to ensure that no entities will spawn on the grid squares where the circle sits

2024-06-05 10:57 UTC, yuning-dev commented on canvas-minigame.js
> +function randomiseCanvasHalf(margin, canvasXY, circleRadius) {
These functions had been created to generate integers / grid coordinates that missed the area where the circle sits. A more elegant solution has been implemented now and they have been erased :)

2024-06-05 11:11 UTC, yuning-dev commented on canvas-minigame.js
> +function updateGridCoordinates(entity) {
Agreed, it's been renamed

2024-06-17 10:22 UTC, JordanGlanfield commented on canvas-minigame.js
> +    checkOverlapWithCircularPerimeter(circularPerimeter) {
Since the object structure you're expecting here is a Mine and it's not intuitive from the name circularPerimeter that you would mean "an object with an outerRadius property", I would probably replace the circular perimeter term with "mine" in the function and parameter name. Ideally the circle would be decoupled from the mine but that would require more refactorings, where I think what you've done already is enough :)

2024-06-17 10:32 UTC, JordanGlanfield commented on canvas-minigame.js
> +                if (this.radius + 7.5 <= 150) {
It's a common code style that global constants are named in "ALL_CAPS_SNAKE_CASE" rather than "camelCase". It makes it clear that you're using a global constant, which differs from using a constant that was declared in a function where it could actually have a different value each time you call the function. You may want to adopt this in your code style in future

2024-06-17 10:34 UTC, JordanGlanfield commented on canvas-minigame.js
> +let gameStateInst = new gameState(false, false)
Leaving it as let makes sense 👍 It should still be renamed to gameState though. Every object you have is technically an instance so it's redundant to put "inst" at the end of the name

2024-06-17 10:37 UTC, JordanGlanfield commented on canvas-minigame.js
> +function addCircleCoordinatesToGridMap(circle) {
This is a much more elegant solution than those util functions you had before :)

2024-06-17 10:40 UTC, JordanGlanfield commented on canvas-minigame.js
> +            let gridString = getGridString(coordinates)
I think this would read better like so:

```
const gridString = getGridString({ x, y })
```

It's fairly clear from context that { x, y } is a coordinates-like object, so adding a variable just for naming it is unnecessary. You can keep the gridString variable since inlining that as well might make the code less readable, up to you. I would change it to const though since it doesn't vary

2024-06-17 10:42 UTC, JordanGlanfield commented on canvas-minigame.js
> +    addCircleCoordinatesToGridMap(circle)
Why do you add the circle coordinates to the grid on every entity spawn? Isn't this function only called when the game is initialised and the circle is in the centre of the grid and hence occupies the same coordinates each time this function is called? Maybe addCircleCoordinatesToGridMap could be called just once before entities are spawned

2024-06-17 10:49 UTC, JordanGlanfield commented on canvas-minigame.js
> +    }
If you just want the entityType to equal the name of the class, you could replace this with `entityType = entity?.constructor.name`. That way adding a new entity type doesn't require you to write more code here. Note that this does change the behaviour, since you no longer restrict which classes can be entities here and "Circle" will no longer be the default entityType.

2024-06-17 10:51 UTC, JordanGlanfield commented on canvas-minigame.js
> +        if (entityType === 'Treat') {
If you follow my suggestion above then change this to `entity instanceof Treat` to make it more robust to changes

2024-06-17 10:52 UTC, JordanGlanfield commented on canvas-minigame.js
> +    grid = new Map
Missing parentheses

2024-06-17 11:03 UTC, JordanGlanfield commented on canvas-minigame.js
> +        }
I noticed that in several places where you change the centre of a treat, you have to remember to update topLeft. This already led to a bug since it's easy to forget to update topLeft when you change it. Instead of having a field called topLeft, why don't you add a getter property? This is kind of like a computed property from Vue. You just add a function to your class like so:

```
get topLeft() {
  return {
    x: this.center.x - (this.size.width / 2),
    y: this.center.y - (this.size.height / 2)
  }
}
```

Then you still access it the same way: `treat.topLeft.x`. You can also remove all the code that updates topLeft, since it will update automatically. There's more detail on getter properties here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

Also note, changing the centre directly already somewhat violates the principle of encapsulation since you're manipulating an object's state directly rather than the telling the object what you want and letting it manipulate its own state. You'll read more about this in Kyle Simpson's books most likely so don't worry about it for now, but just be aware that you need to be careful when manipulating an object's properties since it exposes you to inconsistency issues like this one. We can talk more about this in person if you're interested :)

2024-06-17 11:19 UTC, JordanGlanfield commented on canvas-minigame.js
> +function redrawCanvas() {
There is a lot of overlap of canvas logic between the following functions:
- redrawCanvas
- preDrawingCircle
- handleTreatsCollision
- handleMinesCollision

Each of the following operations are carried out in multiple functions (sometimes a function will carry out an operation, then call a function that carries out the same operation):
- reset the canvas
- draw the circle
- draw the axis
- draw treats
- draw mines

This means there's a lot of redundancy, some performance loss, and it's difficult to understand how your canvas and game logic works and how to debug it. Can you restructure / replace / update those functions such that each of those operations only occurs in your code once?

Tip: do all your state updates and then do all your drawing. E.g., check collision with every treat and every mine and make the appropriate state changes before you do any redrawing. Only once the state is fully up to date do you need to draw the canvas, circle, axis, treats, mines, and star. Happy do discuss this more offline :)

2024-06-17 11:20 UTC, JordanGlanfield commented on canvas-minigame.js
> +function randomiseCanvasHalf(margin, canvasXY, circleRadius) {
Thank you for explaining :)

2024-06-18 08:40 UTC, yuning-dev commented on canvas-minigame.js
> +    addCircleCoordinatesToGridMap(circle)
Good point, addressed now

2024-06-18 08:46 UTC, yuning-dev commented on canvas-minigame.js
> +    }
That is better, cheers

2024-06-18 09:34 UTC, yuning-dev commented on canvas-minigame.js
> +        }
That's a lot better than what I had. I've always thought computed properties in Vue were really cool and useful but felt it was a shame that a similar thing didn't exist for raw JS - so really glad to learn about those :)

2024-06-18 09:35 UTC, yuning-dev commented on canvas-minigame.js
> +        }
It's updated now

2024-06-18 10:23 UTC, yuning-dev commented on canvas-minigame.js
> +function redrawCanvas() {
It's been refactored. I'm quite happy with the result, the code is much more elegant now :)

2024-08-22 11:01 UTC, JordanGlanfield approved these changes
Looks good to me! The flow of game logic is much easier to understand now 👌

2024-08-22 11:01 UTC, JordanGlanfield commented on canvas-minigame.js
> +function redrawCanvas() {
Yeah agreed, it's a big improvement :)

2024-08-22 12:59 UTC, merged